version: "3.7"

services:
  app1:
    container_name: demo-app-1
    image: app1:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
  app2:
    container_name: demo-app-2
    image: app2:0.0.1-SNAPSHOT
    ports:
      - "8081:8080"
