version: "3.7"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "20080:9090"
    command: --config.file=/etc/prometheus/prometheus.yml
  grafana:
    container_name: grafana
    image: grafana/grafana
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    ports:
      - "20081:3000"
