global:
  scrape_interval: 10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: 'demo-apps'
    metrics_path: '/actuator/prometheus' # Application prometheus endpoint
    static_configs:
      - targets: [ 'host.docker.internal:9090', 'host.docker.internal:9091' ] # Application host:port
